#lang racket

(require rackunit)
(require 2htdp/image)
(require lang/posn)
(require "ccsnake.rkt")

(check-equal? (render (game empty 0 0)) (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                                                        SCORE_SIZE SCORE_COLOR)
                                                                  (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR))
                                                            (list (make-posn SCORE_X SCORE_Y)
                                                                  (make-posn GRID_X GRID_Y))
                                                            "left" "top" BACKGROUND))

(check-equal? (render (game (list 3 2 1 0) 1 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (+ GRID_X CELL_WIDTH) GRID_Y)
                                        (make-posn (+ GRID_X (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ GRID_X (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))

(check-equal? (render (game (list 6 5 4 3) 1 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 3) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))

(check-equal? (render (game (list 34 33 32 31) 1 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 38 37 36 35) 1 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ GRID_X CELL_WIDTH) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 2)) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 3)) (+ GRID_Y CELL_WIDTH)))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 41 40 39 38) 1 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 3) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) (+ GRID_Y CELL_WIDTH)))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 69 68 67 66) 1 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) (+ GRID_Y CELL_WIDTH)))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 34 33 32 31) 1 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 1158 1157 1156 1155) 1 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ GRID_X CELL_WIDTH) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 2)) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 3)) (+ GRID_Y (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 1161 1160 1159 1158) 1 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 3) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) (+ GRID_Y (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 1189 1188 1187 1186) 1 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) (+ GRID_Y (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))

(check-equal? (render (game (list 105 70 35 0) 1 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X (+ GRID_Y (* 1 CELL_WIDTH)))
                                        (make-posn GRID_X (+ GRID_Y (* 2 CELL_WIDTH)))
                                        (make-posn GRID_X (+ GRID_Y (* 3 CELL_WIDTH))))
                                  "left" "top" BACKGROUND))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(check-equal? (render (game (list 0 1 2 3) 0 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (+ GRID_X CELL_WIDTH) GRID_Y)
                                        (make-posn (+ GRID_X (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ GRID_X (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))

(check-equal? (render (game (list 3 4 5 6) 0 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 3) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))

(check-equal? (render (game (list 31 32 33 34) 0 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 35 36 37 38) 0 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ GRID_X CELL_WIDTH) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 2)) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 3)) (+ GRID_Y CELL_WIDTH)))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 38 39 40 41) 0 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 3) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) (+ GRID_Y CELL_WIDTH)))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 66 67 68 69) 0 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) (+ GRID_Y CELL_WIDTH)))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 31 32 33 34) 0 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 1155 1156 1157 1158) 0 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ GRID_X CELL_WIDTH) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 2)) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 3)) (+ GRID_Y (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 1158 1159 1160 1161) 0 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 3) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) (+ GRID_Y (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))
(check-equal? (render (game (list 1186 1187 1188 1189) 0 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) (+ GRID_Y (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))

(check-equal? (render (game (list 0 35 70 105) 0 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X (+ GRID_Y (* 1 CELL_WIDTH)))
                                        (make-posn GRID_X (+ GRID_Y (* 2 CELL_WIDTH)))
                                        (make-posn GRID_X (+ GRID_Y (* 3 CELL_WIDTH))))
                                  "left" "top" BACKGROUND))

(check-equal? (render (game (list 143 144 145 146 181 216 251 286) 0 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "seagreen")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 3) (+ GRID_Y (* 4 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 4) (+ GRID_Y (* 4 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 5) (+ GRID_Y (* 4 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 6) (+ GRID_Y (* 4 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 6) (+ GRID_Y (* 5 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 6) (+ GRID_Y (* 6 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 6) (+ GRID_Y (* 7 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 6) (+ GRID_Y (* 8 CELL_WIDTH))))
                                  "left" "top" BACKGROUND))

(check-equal? (render (game (list 286 251 216 181 146 145 144 143) 1 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 3) (+ GRID_Y (* 4 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 4) (+ GRID_Y (* 4 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 5) (+ GRID_Y (* 4 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 6) (+ GRID_Y (* 4 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 6) (+ GRID_Y (* 5 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 6) (+ GRID_Y (* 6 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 6) (+ GRID_Y (* 7 CELL_WIDTH)))
                                        (make-posn (* CELL_WIDTH 6) (+ GRID_Y (* 8 CELL_WIDTH))))
                                  "left" "top" BACKGROUND))

(check-equal? (draw-snake-body (list 3 2 1 0) BACKGROUND) 
              (place-images/align (list
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "seagreen"))
                                  (list
                                   (make-posn GRID_X 0)
                                   (make-posn (+ GRID_X CELL_WIDTH) 0)
                                   (make-posn (+ GRID_X (* CELL_WIDTH 2)) 0)
                                   (make-posn (+ GRID_X (* CELL_WIDTH 3)) 0))
                                  "left" "top" BACKGROUND))
(check-equal? (draw-snake-body (list 6 5 4 3) BACKGROUND)
              (place-images/align (list
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "seagreen"))
                                  (list
                                   (make-posn (* CELL_WIDTH 3) 0)
                                   (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) 0)
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) 0)
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) 0))
                                  "left" "top" BACKGROUND))
(check-equal? (draw-snake-body (list 1161 1160 1159 1158) BACKGROUND) 
              (place-images/align (list
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "seagreen"))
                                  (list
                                   (make-posn (* CELL_WIDTH 3) (+ 0 (* CELL_WIDTH 33)))
                                   (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) (+ 0 (* CELL_WIDTH 33)))
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) (+ 0 (* CELL_WIDTH 33)))
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) (+ 0 (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(check-equal? (draw-snake-body (list 0 1 2 3) BACKGROUND) 
              (place-images/align (list
                                   (square CELL_WIDTH "solid" "seagreen")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green"))
                                  (list
                                   (make-posn GRID_X 0)
                                   (make-posn (+ GRID_X CELL_WIDTH) 0)
                                   (make-posn (+ GRID_X (* CELL_WIDTH 2)) 0)
                                   (make-posn (+ GRID_X (* CELL_WIDTH 3)) 0))
                                  "left" "top" BACKGROUND))
(check-equal? (draw-snake-body (list 3 4 5 6) BACKGROUND)
              (place-images/align (list
                                   (square CELL_WIDTH "solid" "seagreen")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green"))
                                  (list
                                   (make-posn (* CELL_WIDTH 3) 0)
                                   (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) 0)
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) 0)
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) 0))
                                  "left" "top" BACKGROUND))
(check-equal? (draw-snake-body (list 1158 1159 1160 1161) BACKGROUND) 
              (place-images/align (list
                                   (square CELL_WIDTH "solid" "seagreen")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green"))
                                  (list
                                   (make-posn (* CELL_WIDTH 3) (+ 0 (* CELL_WIDTH 33)))
                                   (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) (+ 0 (* CELL_WIDTH 33)))
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) (+ 0 (* CELL_WIDTH 33)))
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) (+ 0 (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))

(check-equal? (next (game (list 3 2 1 0)  RIGHT 0)) (game (list 4 3 2 1)  0 0))
(check-equal? (next (game (list 31 32 33 34)  LEFT 0)) (game (list 30 31 32 33)  LEFT 0))
(check-equal? (next (game (list 105 140 175 210)  UP 0)) (game (list 70 105 140 175)  UP 0))
(check-equal? (next (game (list 210 175 140 105)  DOWN 0)) (game (list 245 210 175 140)  DOWN 0))
(check-equal? (next (game (list 110 145 180 215)  RIGHT 0)) (game (list 111 110 145 180)  RIGHT 0))
(check-equal? (next (game (list 111 110 145 180)  RIGHT 0)) (game (list 112 111 110 145)  RIGHT 0))
(check-equal? (next (game (list 112 111 110 145 180)  RIGHT 0)) (game (list 113 112 111 110 145)  RIGHT 0))
(check-equal? (next (game (list 112 111 110 145 180 215)  RIGHT 0)) (game (list 113 112 111 110 145 180)  RIGHT 0))
(check-equal? (next (game (list 112 111 110 145)  RIGHT 0)) (game (list 113 112 111 110)  RIGHT 0))
(check-equal? (next (game (list 112 111 110 145 180 215 214 213 212)  RIGHT 0))
              (game (list 113 112 111 110 145 180 215 214 213)  RIGHT 0))
(check-equal? (next (game (list 42 41 40 75 110 145 180 215 216 217 218 219 220 255 290 291 292 293 258 223 188 153 152 151 150 149 
                                114 79 80 81 82 83 84)  RIGHT 0))
              (game (list 43 42 41 40 75 110 145 180 215 216 217 218 219 220 255 290 291 292 293 258 223 188 153 152 151 150 149
                          114 79 80 81 82 83)  RIGHT 0))

(check-equal? (next (game (list 38 39 40 75 110 145 180 215 216 217 218 219 220 255 290 291 292 293 258 223 188 153 152 151 150 149 
                                114 79 80 81 82 83 84)  LEFT 0))
              (game (list 37 38 39 40 75 110 145 180 215 216 217 218 219 220 255 290 291 292 293 258 223 188 153 152 151 150 149 
                          114 79 80 81 82 83)  LEFT 0))

(check-equal? (next (game (list 40 75 110 145 180 215 216 217 218 219 220 255 290 291 292 293 258 223 188 153 152 151 150 149 
                                114 79 80 81 82 83 84 85 120 155)  UP 0))
              (game (list 5 40 75 110 145 180 215 216 217 218 219 220 255 290 291 292 293 258 223 188 153 152 151 150 149 
                          114 79 80 81 82 83 84 85 120)  UP 0))

(check-equal? (next (game (list 155 120 85 84 83 82 81 80 79 114 149 150 151 152 153 188 223 258 293 292 291 290 255 220 219 218 
                                217 216 215 180 145 110 75 40)  DOWN 0))
              (game (list 190 155 120 85 84 83 82 81 80 79 114 149 150 151 152 153 188 223 258 293 292 291 290 255 220 219 218
                          217 216 215 180 145 110 75)  DOWN 0))

(check-equal? (next (game (list 254 253 252 217 182 147 112 111 110)  RIGHT 0))
              (game (list 255 254 253 252 217 182 147 112 111)  RIGHT 0))
(check-equal? (next (game (list 109 110 111 112)  LEFT 0)) (game (list 108 109 110 111)  LEFT 0))

