#lang racket

(require rackunit)
(require 2htdp/image)
(require lang/posn)
(require "ccsnake.rkt")

(check-equal? (render (make-game empty 0)) (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                                                           SCORE_SIZE SCORE_COLOR)
                                                                     (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR))
                                                               (list (make-posn SCORE_X SCORE_Y)
                                                                     (make-posn GRID_X GRID_Y))
                                                               "left" "top" BACKGROUND))

(check-equal? (render (make-game (list 0 1 2 3) 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (+ GRID_X CELL_WIDTH) GRID_Y)
                                        (make-posn (+ GRID_X (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ GRID_X (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))

(check-equal? (render (make-game (list 3 4 5 6) 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 3) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))

(check-equal? (render (make-game (list 31 32 33 34) 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))
(check-equal? (render (make-game (list 35 36 37 38) 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ GRID_X CELL_WIDTH) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 2)) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 3)) (+ GRID_Y CELL_WIDTH)))
                                  "left" "top" BACKGROUND))
(check-equal? (render (make-game (list 38 39 40 41) 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 3) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) (+ GRID_Y CELL_WIDTH)))
                                  "left" "top" BACKGROUND))
(check-equal? (render (make-game (list 66 67 68 69) 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) (+ GRID_Y CELL_WIDTH))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) (+ GRID_Y CELL_WIDTH)))
                                  "left" "top" BACKGROUND))
(check-equal? (render (make-game (list 31 32 33 34) 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) GRID_Y)
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) GRID_Y))
                                  "left" "top" BACKGROUND))
(check-equal? (render (make-game (list 1155 1156 1157 1158) 0))
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn GRID_X (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ GRID_X CELL_WIDTH) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 2)) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ GRID_X (* CELL_WIDTH 3)) (+ GRID_Y (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))
(check-equal? (render (make-game (list 1158 1159 1160 1161) 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 3) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) (+ GRID_Y (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))
(check-equal? (render (make-game (list 1186 1187 1188 1189) 0)) 
              (place-images/align (list (text (string-append SCORE_STRING (number->string 0))
                                              SCORE_SIZE SCORE_COLOR)
                                        (rectangle GRID_WIDTH GRID_HEIGHT "outline" GRID_BORDER_COLOR)
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "green")
                                        (square CELL_WIDTH "solid" "seagreen"))
                                  (list (make-posn SCORE_X SCORE_Y)
                                        (make-posn GRID_X GRID_Y)
                                        (make-posn (* CELL_WIDTH 31) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 31) CELL_WIDTH) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 2)) (+ GRID_Y (* CELL_WIDTH 33)))
                                        (make-posn (+ (* CELL_WIDTH 31) (* CELL_WIDTH 3)) (+ GRID_Y (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))

(check-equal? (draw-snake-body (list 0 1 2 3) BACKGROUND) 
              (place-images/align (list
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "seagreen"))
                                  (list
                                   (make-posn GRID_X 0)
                                   (make-posn (+ GRID_X CELL_WIDTH) 0)
                                   (make-posn (+ GRID_X (* CELL_WIDTH 2)) 0)
                                   (make-posn (+ GRID_X (* CELL_WIDTH 3)) 0))
                                  "left" "top" BACKGROUND))
(check-equal? (draw-snake-body (list 3 4 5 6) BACKGROUND)
              (place-images/align (list
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "seagreen"))
                                  (list
                                   (make-posn (* CELL_WIDTH 3) 0)
                                   (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) 0)
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) 0)
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) 0))
                                  "left" "top" BACKGROUND))
(check-equal? (draw-snake-body (list 1158 1159 1160 1161) BACKGROUND) 
              (place-images/align (list
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "green")
                                   (square CELL_WIDTH "solid" "seagreen"))
                                  (list
                                   (make-posn (* CELL_WIDTH 3) (+ 0 (* CELL_WIDTH 33)))
                                   (make-posn (+ (* CELL_WIDTH 3) CELL_WIDTH) (+ 0 (* CELL_WIDTH 33)))
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 2)) (+ 0 (* CELL_WIDTH 33)))
                                   (make-posn (+ (* CELL_WIDTH 3) (* CELL_WIDTH 3)) (+ 0 (* CELL_WIDTH 33))))
                                  "left" "top" BACKGROUND))